# Setup
title: Moon-Akdong's
tagline: "Blog"
description: "개발하고, 살고, 가끔 씁니다."
url: https://moon-akdong.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Moon Jaeyun
  url: https://github.com/moon-akdong
  email:

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
